#!/bin/sh
docker exec -it neo4j bin/neo4j-admin database restore --from-path /backups/neo4j/$1
#docker exec -it neo4j cat data/scripts/jav/restore_metadata.cypher | bin/cypher-shell -u iomz -p 'paper-ironic-gibson-rhino-vertigo-3153' -d system --param "database => 'jav'"
