version: "3.9"
volumes:
  neo4j_data:
services:
  server:
    image: neo4j:5.7.0-enterprise
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    volumes:
      - neo4j_data:/data
      - ./backups:/backups
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
